version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.20.0.10

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"